-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
            popups = true,
            size = 8,
        },
        rounding = 16,
        rounding_power = 2.0,
    },
    general = {
        border_size = 0,
        gaps_in = 3,
        gaps_out = 5,
    },
    input = {
        accel_profile = "",
        sensitivity = 0.0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
