-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
            popups = true,
            size = 8,
        },
        rounding = 16,
        rounding_power = 2.0,
    },
    general = {
        border_size = 2,
        col = {
            active_border = "0xff7daea3",
            inactive_border = "0xaa595959",
        },
        gaps_in = 3,
        gaps_out = 5,
    },
    input = {
        accel_profile = "flat",
        sensitivity = 0.0,
        touchpad = {
            natural_scroll = true,
            scroll_factor = 0.1,
        },
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})

-- Monitors
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "2560x1440@120.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
